#include<stdio.h>
main(){
    printf("\n\t\t*\t\t*");
    printf("\n\t*\t\t*");
    printf("\n*\t\t*");
    printf("\n\t*\t\t*");
    printf("\n\t\t*\t\t*");
    printf("\n");
    printf("\n");
    printf("\n\t*\t*\t*\t*\t*\t*\t*");
    printf("\n");
    printf("\n*\t*\t*\t*\t*\t*\t*\t*");
    printf("\n*\t\t*\t\t\t\t\t*");
    printf("\n*\t\t*\t\t*\t*\t*\t*");
    printf("\n*\t\t*\t\t*\t\t*\t*");
    printf("\n*\t*\t*\t*\t*\t*\t*\t*");
}